# Generated by Django 5.2.1 on 2025-05-15 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'الاثنين'), ('Tue', 'الثلاثاء'), ('Wed', 'الأربعاء'), ('Thu', 'الخميس'), ('Fri', 'الجمعة'), ('Sat', 'السبت'), ('Sun', 'الأحد')], max_length=3)),
                ('week_number', models.IntegerField()),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.workout')),
            ],
            options={
                'unique_together': {('workout', 'day_of_week', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.workout')),
                ('workout_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.workoutday')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('workout_day', 'exercise', 'set_number')},
            },
        ),
    ]
