# Generated by Django 5.2.1 on 2025-05-15 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('workout', 'user', 'day_of_week', 'week_number')},
        ),
    ]
