# Generated by Django 5.2 on 2025-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0002_alter_workoutday_unique_together_workoutday_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutday',
            name='day_of_week',
            field=models.CharField(choices=[('Sat', 'السبت'), ('Sun', 'الأحد'), ('Mon', 'الاثنين'), ('Tue', 'الثلاثاء'), ('Wed', 'الأربعاء'), ('Thu', 'الخميس')], max_length=3),
        ),
    ]
